categories:
  - id: sub-1788772697857
    label: 孝子貓 | omg_workhard
albums:
  - title: 孝子貓 | omg_workard
    category: sub-1788772697857
    link: https://www.youtube.com/@omg_workhard/shorts
    photos:
      - src: https://enchiang.com/images/omg-workhard.jpeg
        caption: https://www.youtube.com/@omg_workhard/shorts
      - src: /images/omg-workhard-ff651496fa.jpg
        caption: https://www.instagram.com/omg_workhard/
      - src: /images/omg-workhard-ff651496fa.jpg
        caption: https://www.tiktok.com/@omg_workhard711
