categories:
  - id: sub-1788772697857
    label: 孝子貓 | omg_workhard
albums:
  - title: 孝子貓 | omg_workard
    category: sub-1788772697857
    link: https://www.youtube.com/@omg_workhard/shorts
    social_links:
      - platform: youtube
        url: https://www.youtube.com/@omg_workhard/shorts
      - platform: instagram
        url: https://www.instagram.com/omg_workhard/
      - platform: tiktok
        url: https://www.tiktok.com/@omg_workhard711
      - platform: facebook
        url: https://www.facebook.com/profile.php?id=61594105254646
      - platform: threads
        url: https://www.threads.com/@omg_workhard?igshid=NTc4MTIwNjQ2YQ==
    photos:
      - src: /images/omg-workhard.jpeg
        caption: null
